services:

  web:
    image: 8105577060/python-multi:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: mongo
    volumes:
      - mongodata:/data/db
    networks:
      - appnet

networks:
  appnet:

volumes:
  mongodata:
